### ISSUE TITLE
Padding correctness

### ISSUE THREAD

**Issue by lshamis** [powturbo/Turbo-Base64#1]
I'm not sure the output is always correct wrt the padding at the end of the generated encoding (though it is still reversible).

```cc
char kBase64Chars[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

char* out = malloc(turbob64len(64) + 1024);
memset(out, 0, turbob64len(64) + 1024);
turbob64enc(kBase64Chars, 64, out);
```

The output:
`
QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLwAAAA==
`
which is 92 char.

The expected output is:
`
QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLw==
`
which is 88 char.

Note also
```cc
turbob64len(64) == 88
```
but will cause an overrun. This seem to be a known issue, since the benchmark over-allocates by `1024`, but I'm not seeing any documentation.

**Comment by powturbo** [comment]
Thanks for reporting. 
I've adjusted now the boundary checking. 
There is no more reading/writing beyond the buffer end.
Please, check again.

**Comment by lshamis** [comment]
Thanks! I think that did it :)

**Comment by lshamis** [comment]
You might want to update the benchmark to not add the 1024.
