### ISSUE TITLE
Remove GPL v2 License

### ISSUE THREAD

**Issue by DimasKovas** [powturbo/Turbo-Base64#10]
Some files (conf.h and time_.h) have GPL v2 License. And it looks like a mistake (since all other files including LICENSE have another license).

If it's a mistake, please, update license text in these files and remove GPL v2 License. It will allow the usage of this library in projects where GPLv2 is incompatible.

Thanks.

**Comment by powturbo** [comment]
GPL header is removed now in the 2 files
