### ISSUE TITLE
restartable algo

### ISSUE THREAD

**Issue by jgm-ktg** [powturbo/Turbo-Base64#16]
Hello,

It is often not feasible to prepare the entire input buffer or the entire output buffer prior to a single call of a transformation algo.

For example, look at zlib API.  User provides input chunks in succession and output chunks in succession.  The entire data to be transformed does not have to be in memory at once.

https://zlib.net/zlib_how.html

Please provide this kind of multi-call API!

**Comment by jgm-ktg** [comment]
Hmm, is it true that processing input in multiples of 3 fulfills this requirement already?

**Comment by powturbo** [comment]
Yes
