### ISSUE TITLE
Padding is not filled correctly for strings of certain size.

### ISSUE THREAD

**Issue by alexey-milovidov** [powturbo/Turbo-Base64#5]
https://github.com/ClickHouse/ClickHouse/issues/9491

**Comment by powturbo** [comment]
Yeah, the last bytes must be handled separately in the EXTAIL macro and not within the avx2/sse loops.
I've now made some changes and it should be fixed now.

**Comment by alexey-milovidov** [comment]
Thank you! It helps.
