### ISSUE TITLE
Maybe a URL Safe variant version?

### ISSUE THREAD

**Issue by terrywh** [powturbo/Turbo-Base64#6]
Maybe a URL Safe variant version? Mapping "+" to "-" And "/" to "_" ?

**Comment by lostangelwangyang** [comment]
修改tb64avx2dec():

    const __m256i delta_asso   = url_safe ?
        _mm256_setr_epi8(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 13, 0, 0, 0, 12,
                         1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 13, 0, 0, 0, 12) : /* no support '/' */
        _mm256_setr_epi8(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 14, 0, 12, 0, 0,
                         1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 14, 0, 12, 0, 0);  /* no support '_' */

    const __m256i delta_values = url_safe ?
        _mm256_setr_epi8(0, 0, 0, 17, 4, -65, -65, -71, -71, 0, 0, -65, -32, -71, 0, 0,
                         0, 0, 0, 17, 4, -65, -65, -71, -71, 0, 0, -65, -32, -71, 0, 0) :
        _mm256_setr_epi8(0, 0, 0, 16, 4, -65, -65, -71, -71, 0, 19, -65, -65, -71, -71, 0,
                         0, 0, 0, 16, 4, -65, -65, -71, -71, 0, 19, -65, -65, -71, -71, 0);
